### PR TITLE
install versioneer to provide full version metadata

### PR DESCRIPTION
**Pull request by pavoljuhas**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Personally I'd rather not use versioneer.

**Comment by pavoljuhas** [comment]
I am starting to test the [split-off-callback](https://github.com/pavoljuhas/databroker-elasticsearch/commits/split-off-callback) branch on Eli's beamline, and it is very useful
to know exact development version which is installed.

If other versioning schemes work better, we can switch to them later once
the code is more stable.

**Comment by CJ-Wright** [comment]
Fair enough

**Comment by pavoljuhas** [comment]
So is it good to merge?

**Comment by CJ-Wright** [comment]
Unless anyone else has issues.

**Pull request merged**
