### PR TITLE
change import name

### PR DESCRIPTION
**Pull request by pavoljuhas**
Change package import name to databroker_elasticsearch.

- avoid import of repository sources when testing installed package.
- move tests out of the package directory; they are not installed.

Resolve https://github.com/NSLS-II/databroker-elasticsearch/issues/2.
Resolve https://github.com/NSLS-II/databroker-elasticsearch/issues/4.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@CJ-Wright - any objections if I merge this in?
I have quite a few more updates that depend on this PR.

**Comment by CJ-Wright** [comment]
No strong complaints from me, although I'm not usually a fan of `src` folders like this (but this isn't a blocking issue)
@stuartcampbell does this meet the databroker standards

**Comment by stuartcampbell** [comment]
I have no strong feelings either way - pinging @NSLS-II/dama in case anyone there does

**Comment by tacaswell** [comment]
I have a preference for installing the tests (so you can run them on an installed from packaging version) but don't have a strong opinion.

**Review by tacaswell — APPROVED** [review]

**Comment by pavoljuhas** [comment]
> I have a preference for installing the tests ...

I prefer that as well, but in this package the tests change ES instance where they create and remove indices.  I feel it is better to prevent their execution within a beamline-deployed package.  As it is the tests are only present in the repo and can be executed either with installed package or on the repository sources (after `python setup.py develop`).

**Pull request merged**
